# THIS IS A DCE CONFIGURATION TEMPLATE
# Please refer to the ConfigurationDocumentation file for assistance in writing a functional configuration file.
# Or, if you are looking for DCEConfig files created by other users, go to: https://github.com/Luca1991/DCEConfigs