name: Build and Release on Tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC environment
      uses: microsoft/setup-msbuild@v1

    - name: Configure CMake
      run: cmake -A Win32 -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Archive Binaries
      run: |
        mkdir DCE-x86
        cp "build/DiscCheckEmuAPIHook/Release/DCEAPIHook.dll" DCE-x86/
        cp "build/DiscCheckEmuLoader/Release/DCELoader.exe" DCE-x86/
        cp "DCEConfig_TEMPLATE.yaml" DCE-x86/DCEConfig.yaml
        cp "README.md" DCE-x86/README.txt
        cp "CHANGELOG.md" DCE-x86/CHANGELOG.txt
        Compress-Archive -Path "DCE-x86/*" -DestinationPath DiscCheckEmu-${{ github.ref_name }}-x86.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: DiscCheckEmu-${{ github.ref_name }}-x86.zip
